import os
import multiprocessing
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import xarray as xr

warnings.filterwarnings("ignore")

import sys

if '__file__' in globals():
    _script_dir = os.path.dirname(os.path.abspath(__file__))
else:
    _script_dir = os.path.abspath(os.path.join(os.getcwd(), 'organization_indices')) if 'organization_indices' not in os.getcwd() else os.getcwd()

if _script_dir not in sys.path:
    sys.path.append(_script_dir)

# Import organization index functions
from run_metrics_periodic_fixed import run_metrics_periodic
from run_metrics import run_metrics

# ============================================================================
# USER CONFIGURATION
# ============================================================================

# Simulation type: 'PINACLES' or 'DP-SCREAM'
SIMULATION_TYPE = 'DP-SCREAM'  # Options: 'PINACLES', 'DP-SCREAM'

# Input concatenated file (generated by concat_dailyfiles.py)
INPUT_FILE_PATH = '/pscratch/sd/w/wcmca1/DP-SCREAM/dx1km_L150km_RCE01_gpu/org_ind/dx1km_L150km_RCE01_gpu_LW_flux_up_at_model_top_2000-01-01_to_2000-04-30.nc'

# Variable name in the netCDF file
OLR_VAR_NAME = 'LW_flux_up_at_model_top'  # For PINACLES: 'toa_lw_up', For DP-SCREAM: 'LW_flux_up_at_model_top'

# Domain information
DOMAIN_SIZE = '150x150'  # e.g., '600x600', '150x150'
RESOLUTION = '1km'       # e.g., '3km', '1km'

# Processing parameters
OLR_THRESHOLD = 173      # W/m² - threshold for deep convection (OLR < threshold)
USE_PERIODIC = True      # Use periodic boundary conditions

# Output configuration
OUTPUT_DIR = f'index_pkl_{DOMAIN_SIZE}_{RESOLUTION}'
OUTPUT_FILENAME = f'df_{SIMULATION_TYPE}_{DOMAIN_SIZE}_{RESOLUTION}_periodic_hourly.pkl'

# Experiment label
EXPERIMENT_LABEL = f'{SIMULATION_TYPE} {DOMAIN_SIZE} {RESOLUTION}'

# Parallelization
# Uses SLURM_CPUS_PER_TASK if running in a batch job, otherwise uses all available CPUs
NUM_WORKERS = int(os.environ.get("SLURM_CPUS_PER_TASK", multiprocessing.cpu_count()))


# ============================================================================
# WORKER FUNCTION
# ============================================================================

def process_time_step(args):
    """
    Worker function to compute organization indices for a single time step.
    This runs in a separate process.
    """
    time_value, image, periodic = args
    
    # Extract date and time information
    date_time = pd.to_datetime(str(time_value))
    yy, mm, dd, hh, mi = date_time.year, date_time.month, date_time.day, date_time.hour, date_time.minute
    
    df_time_tmp = pd.DataFrame({
        'year': [yy], 'month': [mm], 'day': [dd], 'hour': [hh], 'minute': [mi], 'time': [time_value]
    })
    
    # Compute organization metrics
    if periodic:
        dict_org = run_metrics_periodic(np.copy(image))
    else:
        dict_org = run_metrics(np.copy(image))
        
    df_org_tmp = pd.DataFrame(dict_org, index=[0])
    
    return pd.concat([df_time_tmp.reset_index(drop=True), df_org_tmp.reset_index(drop=True)], axis=1)


# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    print(f"==================================================")
    print(f"  Parallel Convective Organization Index Compute  ")
    print(f"==================================================")
    print(f"Experiment: {EXPERIMENT_LABEL}")
    print(f"Number of parallel workers: {NUM_WORKERS}")
    print(f"Output will be saved to: {OUTPUT_DIR}/{OUTPUT_FILENAME}")
    
    # ------------------------------------------------------------------------
    # 1. Load Data
    # ------------------------------------------------------------------------
    print(f"\nLoading data from: {INPUT_FILE_PATH}")
    if not os.path.exists(INPUT_FILE_PATH):
        raise FileNotFoundError(f"Input file not found: {INPUT_FILE_PATH}")
    
    ds = xr.open_dataset(INPUT_FILE_PATH)

    olr_data = ds[OLR_VAR_NAME].copy()
    time_values = olr_data.coords['time'].values
    n_times = len(time_values)
    
    print(f"✓ Data loaded")
    print(f"Data shape: {olr_data.shape}")
    print(f"Time range: {time_values[0]} to {time_values[-1]}")
    print(f"Number of time steps: {n_times}")
    
    # ------------------------------------------------------------------------
    # 2. Prepare Tasks
    # ------------------------------------------------------------------------
    print(f"\nPreparing tasks (converting to binary images)...")
    tasks = []
    
    # We pre-extract the binary image (1/0) for each time step.
    # Passing numpy arrays to multiprocessing workers is very efficient.
    for time_value in time_values:
        ds_time = olr_data.sel(time=time_value)
        image = np.where(ds_time.data < OLR_THRESHOLD, 1, 0).astype(int)
        tasks.append((time_value, image, USE_PERIODIC))
        
    # ------------------------------------------------------------------------
    # 3. Parallel Execution
    # ------------------------------------------------------------------------
    print(f"\nComputing organization indices in parallel...")
    results = []
    
    # We use imap_unordered to yield results as soon as they are ready
    with multiprocessing.Pool(processes=NUM_WORKERS) as pool:
        for i, res in enumerate(pool.imap_unordered(process_time_step, tasks), 1):
            results.append(res)
            # Print progress every 5% or 10 steps, whichever is larger
            progress_step = max(10, n_times // 20)
            if i % progress_step == 0 or i == n_times:
                print(f"  Progress: {i}/{n_times} ({100*i/n_times:.1f}%)")

    print(f"✓ Processing complete!")
    
    # Combine results and sort chronologically (imap_unordered mixes the order)
    df_indices = pd.concat(results, ignore_index=True)
    df_indices = df_indices.sort_values('time').reset_index(drop=True)
    
    # ------------------------------------------------------------------------
    # 4. Summary Statistics
    # ------------------------------------------------------------------------
    print("\n" + "="*70)
    print("SUMMARY STATISTICS")
    print("="*70)
    
    summary_metrics = ['number', 'mean_area', 'Iorg', 'SCAI', 'MCAI', 'COP', 'ROME', 'Lorg']
    for metric in summary_metrics:
        if metric in df_indices.columns:
            print(f"\n{metric}:")
            print(f"  Mean: {df_indices[metric].mean():.3f}")
            print(f"  Std:  {df_indices[metric].std():.3f}")
            print(f"  Min:  {df_indices[metric].min():.3f}")
            print(f"  Max:  {df_indices[metric].max():.3f}")
            
    # ------------------------------------------------------------------------
    # 5. Save Results
    # ------------------------------------------------------------------------
    output_dir_path = Path(OUTPUT_DIR)
    output_dir_path.mkdir(exist_ok=True, parents=True)
    output_path = output_dir_path / OUTPUT_FILENAME
    
    df_indices.to_pickle(output_path)
    
    print("\n" + "="*70)
    print("RESULTS SAVED")
    print("="*70)
    print(f"File: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024:.1f} KB")
    print(f"Rows: {len(df_indices)}")
    print(f"Columns: {len(df_indices.columns)}")
    print("✓ Save complete!")


if __name__ == '__main__':
    main()
